export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';

export interface EndpointDoc {
  id: string;
  method: HttpMethod;
  path: string;
  description: string;
  auth: boolean;
  role?: string;
  requestBody?: Record<string, { type: string; required: boolean; description: string }>;
  responseExample: unknown;
  group: string;
}

export const API_ENDPOINTS: EndpointDoc[] = [
  {
    id: 'auth-register',
    method: 'POST',
    path: '/api/auth/register',
    group: 'Auth',
    description: 'Register a new user account. Returns a JWT token and user object.',
    auth: false,
    requestBody: {
      name: { type: 'string', required: true, description: 'Full name' },
      email: { type: 'string', required: true, description: 'Unique email address' },
      password: { type: 'string', required: true, description: 'Password (min 6 chars)' },
      role: { type: 'student | teacher | admin', required: true, description: 'User role' },
      department: { type: 'string', required: false, description: 'Department or faculty' },
    },
    responseExample: {
      token: 'uuid-session-token',
      user: { id: 'u1', name: 'Alice Smith', email: 'alice@example.com', role: 'student', joinedAt: '2026-02-24' },
    },
  },
  {
    id: 'auth-login',
    method: 'POST',
    path: '/api/auth/login',
    group: 'Auth',
    description: 'Authenticate a user with email and password. Returns a session token.',
    auth: false,
    requestBody: {
      email: { type: 'string', required: true, description: 'Registered email address' },
      password: { type: 'string', required: true, description: 'Account password' },
    },
    responseExample: { token: 'uuid-session-token', user: { id: 'u1', name: 'Alice Smith', role: 'student' } },
  },
  {
    id: 'profile-get',
    method: 'GET',
    path: '/api/users/profile',
    group: 'Profile & Users',
    description: 'Retrieve the profile of the authenticated user.',
    auth: true,
    responseExample: {
      id: 'u1',
      name: 'Alice Smith',
      email: 'alice@example.com',
      role: 'student',
      department: 'Science',
      joinedAt: '2026-01-20',
    },
  },
  {
    id: 'profile-put',
    method: 'PUT',
    path: '/api/users/profile',
    group: 'Profile & Users',
    description: "Update the authenticated user's profile information.",
    auth: true,
    requestBody: {
      name: { type: 'string', required: false, description: 'Display name' },
      department: { type: 'string', required: false, description: 'Department' },
      phone: { type: 'string', required: false, description: 'Phone number' },
      bio: { type: 'string', required: false, description: 'Short biography' },
    },
    responseExample: { id: 'u1', name: 'Alice Smith', department: 'Engineering', phone: '+1 555-9999' },
  },
  {
    id: 'exams-post',
    method: 'POST',
    path: '/api/exams',
    group: 'Exams',
    description: 'Create a new exam. Restricted to admin and teacher roles.',
    auth: true,
    role: 'admin / teacher',
    requestBody: {
      title: { type: 'string', required: true, description: 'Exam title' },
      description: { type: 'string', required: true, description: 'Description' },
      classId: { type: 'string', required: true, description: 'Target class ID' },
      duration: { type: 'number', required: true, description: 'Duration in minutes' },
      totalMarks: { type: 'number', required: true, description: 'Total marks available' },
      passingMarks: { type: 'number', required: true, description: 'Minimum marks to pass' },
      startDate: { type: 'ISO 8601 datetime', required: true, description: 'Exam start' },
      endDate: { type: 'ISO 8601 datetime', required: true, description: 'Exam end' },
      status: { type: 'draft | published | completed', required: true, description: 'Status' },
      questions: { type: 'Question[]', required: true, description: 'Array of questions' },
    },
    responseExample: {
      id: 'e10',
      title: 'Midterm Exam',
      classId: 'c1',
      duration: 60,
      totalMarks: 100,
      status: 'draft',
      questions: [{ text: 'Solve 2 + 2', type: 'mcq', topic: 'Arithmetic', marks: 5 }],
    },
  },
  {
    id: 'exams-get',
    method: 'GET',
    path: '/api/exams',
    group: 'Exams',
    description: 'Retrieve exams accessible to the authenticated user (filtered by role).',
    auth: true,
    responseExample: [{ id: 'e1', title: 'Algebra Midterm', classId: 'c1', status: 'completed', duration: 60, totalMarks: 100 }],
  },
  {
    id: 'exams-get-id',
    method: 'GET',
    path: '/api/exams/{exam_id}',
    group: 'Exams',
    description: 'Retrieve a single exam by ID, including all questions.',
    auth: true,
    responseExample: {
      id: 'e1',
      title: 'Algebra Midterm',
      questions: [{ id: 'q1', text: 'What is 2+2?', type: 'mcq', topic: 'Arithmetic', options: ['3', '4', '5'], correctAnswer: '4', marks: 10 }],
    },
  },
  {
    id: 'results-submit',
    method: 'POST',
    path: '/api/results/submit',
    group: 'Results',
    description: 'Submit student answers. Auto-grades MCQ questions server-side.',
    auth: true,
    role: 'student',
    requestBody: {
      examId: { type: 'string', required: true, description: 'Exam being submitted' },
      answers: { type: 'Answer[]', required: true, description: 'Array of { questionId, answer }' },
      submittedAt: { type: 'ISO 8601 datetime', required: true, description: 'Submission timestamp' },
      questionTelemetry: { type: 'QuestionTelemetry[]', required: false, description: 'Per-question time spent and interaction metrics for new attempts' },
    },
    responseExample: { id: 's5', examId: 'e1', studentId: 'u4', status: 'submitted', submittedAt: '2026-02-24T10:30:00' },
  },
  {
    id: 'results-student',
    method: 'GET',
    path: '/api/results/student/{student_id}',
    group: 'Results',
    description: 'Retrieve all exam results for a specific student.',
    auth: true,
    responseExample: [{ id: 's1', examId: 'e1', totalScore: 87, percentage: 87, grade: 'A', status: 'graded' }],
  },
  {
    id: 'admin-exams',
    method: 'GET',
    path: '/api/admin/exams',
    group: 'Admin & Reporting',
    description: 'Admin: retrieve all exams with submission counts and average scores.',
    auth: true,
    role: 'admin',
    responseExample: [{ id: 'e1', title: 'Algebra Midterm', status: 'completed', submissionCount: 5, averageScore: 78 }],
  },
  {
    id: 'admin-results',
    method: 'GET',
    path: '/api/admin/results',
    group: 'Admin & Reporting',
    description: 'Admin: retrieve all submissions enriched with student names and exam titles.',
    auth: true,
    role: 'admin',
    responseExample: [{ id: 's1', studentName: 'Alice Smith', examTitle: 'Algebra Midterm', percentage: 87, grade: 'A', status: 'graded' }],
  },
  {
    id: 'admin-logs',
    method: 'GET',
    path: '/api/admin/logs',
    group: 'Admin & Reporting',
    description: 'Admin: inspect recent request logs and audit logs from the logging database.',
    auth: true,
    role: 'admin',
    responseExample: {
      requestSummary: { totalRequests: 42, failedRequests: 2, averageDurationMs: 31 },
      requestLogs: [{ method: 'GET', path: '/api/health', statusCode: 200, durationMs: 8 }],
    },
  },
  {
    id: 'admin-violations',
    method: 'GET',
    path: '/api/admin/violations',
    group: 'Admin & Reporting',
    description: 'Admin: view anti-cheat violation summaries across all exams and case outcomes.',
    auth: true,
    role: 'admin',
    responseExample: {
      summary: { totalViolations: 8, impactedStudents: 3, pendingCases: 2 },
      rows: [{ examTitle: 'Algebra Midterm', studentName: 'Alice Smith', violationCount: 3, outcome: 'pending' }],
    },
  },
  {
    id: 'reports-performance',
    method: 'GET',
    path: '/api/reports/exam-performance',
    group: 'Admin & Reporting',
    description: 'Per-exam performance stats: averages, highest/lowest, pass/fail counts.',
    auth: true,
    role: 'admin / teacher',
    responseExample: [{ examId: 'e1', examTitle: 'Algebra Midterm', totalSubmissions: 5, averageScore: 78, highestScore: 95, lowestScore: 55, passCount: 4, failCount: 1 }],
  },
  {
    id: 'reports-passfail',
    method: 'GET',
    path: '/api/reports/pass-fail',
    group: 'Admin & Reporting',
    description: 'Overall and per-exam pass/fail rates for dashboard analytics.',
    auth: true,
    role: 'admin / teacher',
    responseExample: {
      overall: { total: 13, passed: 10, failed: 3, passRate: 76.9 },
      byExam: [{ examId: 'e1', examTitle: 'Algebra Midterm', passed: 4, failed: 1, passRate: 80 }],
      byClass: [{ classId: 'c1', className: 'Mathematics 101', passed: 7, failed: 2, passRate: 77.8 }],
    },
  },
  {
    id: 'reports-question-analytics',
    method: 'GET',
    path: '/api/reports/question-analytics',
    group: 'Admin & Reporting',
    description: 'Question-level analytics including difficulty, common wrong answers, time spent, and weak topics by class.',
    auth: true,
    role: 'admin / teacher',
    responseExample: {
      generatedAt: '2026-04-20T09:30:00Z',
      coverage: { totalSubmissions: 18, telemetryEnabledSubmissions: 12, totalQuestions: 30, topicTaggedQuestions: 24 },
      hardestQuestions: [{ questionId: 'q1', questionText: 'Factor x^2 - 9', averageScorePct: 38, averageTimeSpentSeconds: 92 }],
      slowestQuestions: [{ questionId: 'q7', questionText: 'Explain your proof', averageScorePct: 61, averageTimeSpentSeconds: 214 }],
      commonWrongAnswers: [{ questionId: 'q3', option: 'B', count: 7, shareOfIncorrectPct: 58.3 }],
      weakTopicsByClass: [{ classId: 'c1', className: 'Mathematics 101', topic: 'Factoring', averageScorePct: 41.7, averageTimeSpentSeconds: 121 }],
    },
  },
];
